#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Feb 01 12:31:57 IST 2024
# SW Build 3173277 on Wed Apr  7 05:07:21 MDT 2021
#
# IP Build 3174024 on Wed Apr  7 23:42:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_binary_adder_behav -key {Behavioral:sim_1:Functional:tb_binary_adder} -tclbatch tb_binary_adder.tcl -view /media/satvik/Study/M_tech/IITB/ARM_SoC_Design_Workshop/Lab_2/Vivado/Binary Adders/tb_binary_adder_behav.wcfg -log simulate.log"
xsim tb_binary_adder_behav -key {Behavioral:sim_1:Functional:tb_binary_adder} -tclbatch tb_binary_adder.tcl -view /media/satvik/Study/M_tech/IITB/ARM_SoC_Design_Workshop/Lab_2/Vivado/Binary Adders/tb_binary_adder_behav.wcfg -log simulate.log

