webtalk_init -webtalk_dir /media/satvik/Study/GitHub/Verilog_practice/Primitive_Gates/Primitive_Gates/Primitive_Gates.sim/sim_1/behav/xsim/xsim.dir/tb_primitive_gates_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 31 22:34:24 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3173277" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "57330c07-f1b2-41c4-8f42-54e2b024ec67" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1b573be7c01a40279bf176012808c68a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3597.560 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115032_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1053696401 -regid "" -xml /media/satvik/Study/GitHub/Verilog_practice/Primitive_Gates/Primitive_Gates/Primitive_Gates.sim/sim_1/behav/xsim/xsim.dir/tb_primitive_gates_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/satvik/Study/GitHub/Verilog_practice/Primitive_Gates/Primitive_Gates/Primitive_Gates.sim/sim_1/behav/xsim/xsim.dir/tb_primitive_gates_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/satvik/Study/GitHub/Verilog_practice/Primitive_Gates/Primitive_Gates/Primitive_Gates.sim/sim_1/behav/xsim/xsim.dir/tb_primitive_gates_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
